version: "3.8"

volumes:
  mongo_vol:

services:
  mongo:
    image: mongo
    restart: always
    container_name: container-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - mongo-compose-network
    volumes:
      - mongo_vol:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:admin@mongo:27017/
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge
