apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: do-pvc
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 5Gi
