apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resource
spec:
  hard: #o total de limites definidos nos resources dsos Pods/Containers é permitido ate os valores abaixo
    pods: "12" # 12 pods para o namespace default
