apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-conversao #vai pegar todos os pods que tem app = api-conversao
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP #default é clusterIP, ira gerar conexao entre pods internamente no cluster kubernetes, atraves do service ClusterIP. Ele sera responsavel para fazer o balanceamento tambem.
