apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: ExternalName #default é clusterIP, ira gerar conexao entre pods internamente no cluster kubernetes, atraves do service ClusterIP. Ele sera responsavel para fazer o balanceamento tambem.
  externalName: veronez.dev
