apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
  namespace: back-end
data:
  Mongo__Port: "27017"
  Mongo__DataBase: admin
  Mongo__Host: mongo-service
  MONGO_INITDB_ROOT_USERNAME: mongouser
  MONGO_INITDB_ROOT_PASSWORD: mongopwd
