apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-conversao #vai pegar todos os pods que tem app = api-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
