version: "3"

volumes:
  redis_vol:

services:
  redis:
    container_name: redis
    hostname: redis
    image: redis
    volumes:
      - redis_vol:/data
    networks:
      - redis-compose-network

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8084:8081"
    networks:
      - redis-compose-network

networks:
  redis-compose-network:
    driver: bridge
