apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-conversao #vai pegar todos os pods que tem app = api-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort #default é clusterIP, ira gerar conexao entre pods internamente no cluster kubernetes, atraves do service ClusterIP. Ele sera responsavel para fazer o balanceamento tambem.
#kubectl port-forward --address 0.0.0.0 service/api-service 31967:80
