apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-service
  namespace: devpedelogo
spec:
  selector:
    app: {{ .Release.Name }}-api
  ports:
  - port: 80
    targetPort: 80
  type: {{ .Values.api.serviceType }}
