apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  {{- range .Values.api.ingress }}
  - host: {{ . }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ $.Release.Name }}-api-service
            port: 
              number: 80
  {{- end -}}
