{{- if empty .Values.mongodb.existSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-secret
  namespace: devpedelogo
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.credentials.userName | b64enc | quote }} ## converte o texto para base64 e  devolve o base64 em forma de texto
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.credentials.userPassword  | b64enc | quote }}
{{- end}}