apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-api-configmap
  namespace: devpedelogo
data:
  Mongo__DataBase:  {{ .Values.mongodb.auth.database }}
  Mongo__Host: {{ template "mongodb.serviceName" . }}
