apiVersion: v1
kind: Service
metadata:
  name: {{ template "mongodb.serviceName" . }}
  namespace: devpedelogo
spec:
  type: ExternalName
  externalName: {{ template "mongodb.serviceName" . }}.default.svc.cluster.local
