apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-pedelogo-deployment
  namespace: back-end
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: desenvolvimentodaian/pedelogo-catalogo:v1.0.0
          ports:
            - containerPort: 80
          env:
            - name: Mongo__Host
              value: mongo-service
            - name: Mongo__User
              value: mongouser
            - name: Mongo__Password
              value: mongopwd
            - name: Mongo__Port
              value: "27017"
            - name: Mongo__DataBase
              value: admin
