apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-versao
spec:
  replicas: 10
  selector:
    matchLabels:
      app: api-versao
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 #quantos pods eu posso criar a mais, do que eu tenho no kubernetes atualmente
      maxUnavailable: 0 #quantos pods eu posso matar, para fazer a troca desejada
  template:
    metadata:
      annotations:
        prometeus.io/scrape: "true"
        prometheus.io/port: "8080"
      labels:
        app: api-versao
    spec:
      containers:
      - name: api-versao
        image: kubedevio/api-versao:v1
        resources: {}
        ports:
        - containerPort: 8080
