apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-pedelogo-deployment
  namespace: back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        - name: init-pod
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              "until nslookup mongo-service; do echo Aguardando o Banco de Dados; sleep 2; done",
            ]
      containers:
        - name: api
          image: desenvolvimentodaian/pedelogo-catalogo:v1.0.0
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 32Mi
              cpu: 150m
            limits:
              memory: 64Mi
              cpu: 500m
          livenessProbe: #verificar a sauda de pod
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            periodSeconds: 5 # de quanto em quanto tempo vou fazer o teste
            timeoutSeconds: 1 #quanto tempo que espera ter uma resposta
            failureThreshold: 3 #quantas vezes vai ser considerado erro
          readinessProbe: #verifica se esta pronto para receber requisicoes
            httpGet:
              path: /read
              port: 80
              scheme: HTTP
            periodSeconds: 5 # de quanto em quanto tempo vou fazer o teste
            timeoutSeconds: 1 #quanto tempo que espera ter uma resposta
            failureThreshold: 3 #quantas vezes vai ser considerado erro
            #successThreshold: 1 #quantos sucessos consecutivos preciso ter, para zerar a quantidade de falhas
          startupProbe: #verifica se o pod pode ser iniciado
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            periodSeconds: 30 # x tentativas a caxa x segundos do failure para a aplicacao startar
            failureThreshold: 10 #quantas vezes vai ser considerado erro
          envFrom:
            - configMapRef:
                name: api-configmap
          env:
            - name: Mongo__User
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_USERNAME
                  name: mongodb-secret
            - name: Mongo__Password
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_PASSWORD
                  name: mongodb-secret
